name: Build EcoRoot Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-container.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ecorootacr2026.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push EcoRoot backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ecorootacr2026.azurecr.io/ecoroot-backend:v1
            ecorootacr2026.azurecr.io/ecoroot-backend:latest